on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
    
    env:
      LINZ_BASEMAP_KEY: ${{ secrets.LINZ_BASEMAP_KEY }}  
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

       - name: Install Quarto Extension "simplemenu"
        run: |
          quarto add martinomagnifico/quarto-simplemenu
          
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: nzfss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}